### ISSUE TITLE
NullPointerException after update to 0.9

### ISSUE THREAD

**Issue by greuelpirat** [antlr/jetbrains-plugin-st4#39] opened 2021-10-17 06:27 UTC
Just updated to `0.9`. Got following exception:

```
com.intellij.diagnostic.PluginException: Cannot create extension (class=org.antlr.jetbrains.st4plugin.highlight.STColorSettingsPage) [Plugin: org.antlr.jetbrains.st4plugin]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:934)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:88)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:489)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:437)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:264)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:35)
	at com.jetbrains.rd.platform.daemon.TextAttributesKeysStorage.s(TextAttributesKeysStorage.kt:36)
	at com.jetbrains.rd.platform.daemon.TextAttributesKeysStorage.register(TextAttributesKeysStorage.kt:27)
	at com.jetbrains.rd.platform.daemon.TextAttributesRegistrationHost.getTextAttributesKey(TextAttributesRegistrationHost.kt:40)
	at com.jetbrains.rdclient.daemon.components.FrontendHighlighterRegistrationHost.S(FrontendHighlighterRegistrationHost.kt:159)
	at com.jetbrains.rdclient.daemon.components.FrontendHighlighterRegistrationHost.access$patchIdeaColorsScheme(FrontendHighlighterRegistrationHost.kt:37)
	at com.jetbrains.rdclient.daemon.components.FrontendHighlighterRegistrationHost$handleDefaultRegistry$1.invoke(FrontendHighlighterRegistrationHost.kt:79)
	at com.jetbrains.rdclient.daemon.components.FrontendHighlighterRegistrationHost$handleDefaultRegistry$1.invoke(FrontendHighlighterRegistrationHost.kt:37)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.framework.impl.RdSignal.onWireReceived(RdSignal.kt:42)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:55)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:97)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:18)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:23)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:141)
	at com.intellij.codeWithMe.ClientId.withClientId(ClientId.kt)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:81)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.intellij.diagnostic.PluginException: Cannot create class org.antlr.jetbrains.st4plugin.highlight.STColorSettingsPage (classloader=PluginClassLoader(plugin=PluginDescriptor(name=StringTemplate v4, id=org.antlr.jetbrains.st4plugin, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-1\213.4928.4.plugins\jetbrains-plugin-st4, version=0.9, package=null, isBundled=false), packagePrefix=null, instanceId=15, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:872)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.java:99)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:116)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:66)
	... 52 more
Caused by: java.lang.ExceptionInInitializerError
	at org.antlr.jetbrains.st4plugin.highlight.STColorSettingsPage.<clinit>(STColorSettingsPage.java:19)
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:482)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:833)
	... 55 more
Caused by: java.lang.NullPointerException
	at org.antlr.jetbrains.st4plugin.psi.STGroupTokenTypes.getTokenElementType(STGroupTokenTypes.java:23)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.antlr.jetbrains.st4plugin.highlight.STGroupSyntaxHighlighter.<clinit>(STGroupSyntaxHighlighter.java:39)
	... 59 more
```

**Comment by greuelpirat** [comment] 2021-10-17 06:28
This exception comes up on the welcome screen (before loading solution)

**Comment by greuelpirat** [comment] 2021-10-18 03:23
I can not find `Code With Me` either. But now I can also not reproduce the exception at all. I have no idea why it came up in the first place. I do not work with it. Sorry, I can not help :-(

**Comment by bjansen** [comment] 2021-10-30 15:13
I'll close the issue as "can't reproduce". Feel free to reopen if it happens again.

**Closed by bjansen** 2021-10-30 15:13 UTC
Labels: bug
